[project]
name = "makeev-m26-555"
version = "0.1.0"
description = ""
authors = [{ name = "VladimirMakeev", email = "VMakeev@alfabank.ru" }]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "prompt>=0.4.1,<0.5.0",
    "sqlparse (>=0.6.0,<0.7.0)",
    "prettytable (>=3.18.0,<4.0.0)",
    "sqlglot (>=30.20.0,<31.0.0)",
]

[project.scripts]
project = "src.primitive_db.main:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv]

[tool.uv.build-backend]
module-name = ["src"]
module-root = ""


[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]


[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
[dependency-groups]
dev = [
    "ruff (>=0.16.8,<0.17.0)"
]
